### ISSUE TITLE
vendor/autoload.php not found

### ISSUE THREAD

**Issue by depuits** [akmolina28/last-watch-ai#1]
When running the containers and going to the site I'm getting the following error:

```
Warning: require(/var/www/app/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/app/public/index.php on line 24

Fatal error: require(): Failed opening required '/var/www/app/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/app/public/index.php on line 24
```

After inspecting the container I could not find the file within the container. I'm running the containers on debian.

**Comment by akmolina28** [comment]
Did you build from source? I just checked the latest release and the vendor autoload is there.

It could be a permission problem due to differences in your file system. If you shell into the container you should see the file at /var/www/app/vendor. 

This file is generated by composer and often these errors will happen on a new setup if composer install was not run. I did run it for the official release but if you're building from source you might run into this. You could try running the install yourself to see if the problem goes away:

`docker-compose run --rm composer install --optimize-autoloader --no-dev`

**Comment by depuits** [comment]
The issue was completely my fault. In stead of using the release zip I was using the git repository directly.
