### ISSUE TITLE
warning: latest release zip appears to use backslashes as path separators

### ISSUE THREAD

**Issue by depuits** [akmolina28/last-watch-ai#5]
When unzipping in linux I get following warning `warning:  last-watch-ai-latest.zip appears to use backslashes as path separators`. Apparently this has to do with the zip program being used ([https://superuser.com/a/1382853/702386](https://superuser.com/a/1382853/702386))

**Comment by akmolina28** [comment]
This is good info, thanks for reporting. I haven't run into this problem but I'm sure this is because I have been using Windows to build the releases.

For now, I am just going to recommend installing from source on Linux. I have had success installing from source and from releases, but I feel that installing from source is better for right now because it makes future upgrades much easier.

See here: https://kleypot.com/last-watch-ai-ubuntu-installation-and-upgrading/

Eventually I plan on standing up a build server to smooth out these issues with the releases. I'd love to have a one-liner that does the upgrade whether you are on windows or linux.

**Comment by depuits** [comment]
When installing from the source this is indeed a none issue. Thanks for the great guide.
