### ISSUE TITLE
Build failing?

### ISSUE THREAD

**Issue by andrepintorj** [akmolina28/last-watch-ai#57]
Hello, I'm following the procedure step by step and looks like there is an issue happening when building the containers.

`
Successfully built b07eac5f96d9
Successfully tagged last-watch-ai_artisan:latest
WARNING: Image for service artisan was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating last-watch-ai_artisan_run ... done
Route cache cleared!
Routes cached successfully!
Creating last-watch-ai_artisan_run ... done

In KeyGenerateCommand.php line 96:                                                                         
  file_put_contents(/var/www/app/.env): failed to open stream: Operation not permitted  
                                                                                        
ERROR: 1
`

If I try to run the stack after that error, I face an error 500 message with no helpful debug. I'll try to dig a bit more on this.

**Comment by akmolina28** [comment]
What OS are you using?

It looks like the generate key step is failing because the laravel .env file is missing from the src folder or is unreadable. (Note that this .env file is different from the .env file in the root level of the project.)

The first command in the build script creates this file:

```
$ sudo cp src/.env.example src/.env
```

Later in the script, the generate key command updates the APP_KEY setting in the src/.env file:

```
$ sudo docker-compose run --rm artisan key:generate
```

I'm not sure what is going wrong on your end, but just to make sure nothing was broken, I fired up a fresh ubuntu container and ran through the steps in the README. Everything is working fine and I could not reproduce your problem.

I would suggest removing the `&&` from the build script and running each command individually. After running the `cp` command at the beginning, check to make sure the .env file is readable in the src directory before proceeding on.

**Comment by andrepintorj** [comment]
So, the issue was really on the src/.env file. I'm running on OS X and looks like when I issue

`$ sudo cp src/.env.example src/.env`

it generates the src/.env file with the root user's permission, making it unreadable by my own user. After I fixed that file's permission to my own user, everything ran smoothly!

Maybe changing the documentation without sudo, would solve the reported problem:
`cp src/.env.example src/.env`

**Comment by akmolina28** [comment]
Excellent, thanks for replying.

I have been waiting to hear from someone trying this out on Mac. Let me know how it works for you!
